version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ac_todos
    ports:
      - "3308:3306"
    volumes:
      - ./resources:/docker-entrypoint-initdb.d # files (.sh, .sql, .sql.gz) executed in alphabetical order